name: deploy to lambda
on: [push]
jobs:
  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v2
      - name: Zip source
        run: cd src && zip -r ../release.zip ./* && cd ..
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: colorschemes_dev-worker
          zip_file: release.zip
